"""Add user timestamp

Revision ID: 0aa72dbaad28
Revises: 452764cdfc31
Create Date: 2023-05-03 01:18:51.242823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0aa72dbaad28"
down_revision = "452764cdfc31"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("users", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    # ### end Alembic commands ###
