version: "3.9"
services:
  app_devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    # Overrides default command so things don't shut down after the process ends
    command: sleep infinity